version: "3.9"

services:
  backend:
    build: ./backend
    container_name: ethfee-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: ethfee-frontend
    ports:
      - "8080:3000"
    env_file:
      - .env
    depends_on:
      - backend
    restart: unless-stopped
