version: "3.9"

services:
  redis:
    image: redis:7
    container_name: ethfee-redis
    # ports:
    #   - "6379:6379"
    volumes:
      - ./redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: ethfee-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: ethfee-frontend
    ports:
      - "8080:3000"
    env_file:
      - .env
    depends_on:
      - backend
    restart: unless-stopped
