version: "3.9"

services:
  # ─────────── Redis ───────────
  redis:
    image: redis:7
    container_name: ethfee-redis
    volumes:
      - ./redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]
    restart: unless-stopped

  # ─────────── FastAPI / backend ───────────
  backend:
    build: ./backend
    container_name: ethfee-backend
    ports:
      - "8000:8000"
    env_file:
      - .env                     # still fine here
    depends_on:
      - redis
    restart: unless-stopped

  # ─────────── Next.js / frontend ───────────
  frontend:
    platform: "linux/amd64"
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    container_name: ethfee-frontend
    ports:
      - "8080:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    depends_on:
      - backend
    restart: unless-stopped
